version: '3.9'
services:
  nuxt:
    build:
      context: ./
      args:
        WORKDIR: front
    ports:
      - 3030:3000
    volumes:
      - .:/front
    working_dir: /front
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn install && yarn run generate:host && yarn run start:host"
