version: '3.8'
services:
  nuxt:
    build:
      context: ./
      args:
        WORKDIR: front
    ports:
      - 3000:3000
    volumes:
      - .:/front
    working_dir: /front
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn run dev:host"
