import Prism from 'prismjs'
// テーマ
import 'prismjs/themes/prism.css'

// 言語ハイライト
import 'prismjs/components/prism-bash'
import 'prismjs/components/prism-docker'
import 'prismjs/components/prism-kotlin'
import 'prismjs/components/prism-python'
import 'prismjs/components/prism-sql'
import 'prismjs/components/prism-swift'
import 'prismjs/components/prism-yaml'
import 'prismjs/components/prism-rust'
import 'prismjs/components/prism-c'
import 'prismjs/components/prism-nasm'
import 'prismjs/components/prism-ruby'
import 'prismjs/components/prism-go'
import 'prismjs/components/prism-markup'
import 'prismjs/components/prism-css'
import 'prismjs/components/prism-csharp'
import 'prismjs/components/prism-cpp'
import 'prismjs/components/prism-java'
import 'prismjs/components/prism-javascript'
import 'prismjs/components/prism-typescript'
import 'prismjs/components/prism-jsx'
import 'prismjs/components/prism-sass'
import 'prismjs/components/prism-json'
import 'prismjs/components/prism-scss'
import 'prismjs/components/prism-vim'
import 'prismjs/components/prism-toml'
import 'prismjs/components/prism-haml'
import 'prismjs/components/prism-markdown'
import 'prismjs/components/prism-cobol'
import 'prismjs/components/prism-lua'
import 'prismjs/components/prism-brainfuck'
import 'prismjs/components/prism-scala'
import 'prismjs/components/prism-uri'
import 'prismjs/components/prism-csv'
import 'prismjs/components/prism-dart'
import 'prismjs/components/prism-graphql'
import 'prismjs/components/prism-go-module'
import 'prismjs/components/prism-ignore'
import 'prismjs/components/prism-ini'
import 'prismjs/components/prism-perl'
import 'prismjs/components/prism-visual-basic'
import 'prismjs/components/prism-matlab'
import 'prismjs/components/prism-tsx'
import 'prismjs/components/prism-markup-templating'
import 'prismjs/components/prism-php'

// 機能拡張

export default Prism
